# Generated by Django 4.1.5 on 2023-01-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(default="Tending my grove", max_length=255),
        ),
    ]
