# Generated by Django 4.1.5 on 2023-01-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="exp",
            field=models.IntegerField(default=0),
        ),
    ]
